Alterações realizadas entre 29/02 e 13/03
nilsonLazarin/WeGIA pull request #24
Opened 2024-03-13 10:59 UTC by GabrielPintoSouza

Criação de duas novas tabelas no banco de dados, aviso e aviso_notificacao.
Necessária a criação de um usuário que seja um funcionário com cargo de "Enfermeiro(a)" ou "Téc. Enfermagem" para testar a implementação da funcionalidade de notificação no servidor em produção, ele deve ter acesso ao módulo de saúde e poder realizar as ações de ler, gravar e executar.

2024-03-14 14:00 UTC, nilsonLazarin requested changes
Para os ajustes necessários

2024-03-14 14:00 UTC, nilsonLazarin commented on dao/AvisoNotificacaoDAO.php
Atrele as verificações com a tabela de permissões.
Busque os cargos que possuem permissão mínima de leitura no módulo saúde.

2024-03-14 14:00 UTC, nilsonLazarin commented on html/header.php
Neste caso idem. Verificar se o cargo do usuário atual possue permissão mínima de leitura no Módulo Saúde.

2024-03-18 14:07 UTC, GabrielPintoSouza commented
Funcionários cujo o CPF foi registrado no formato 00000000000 ao invés de 000.000.000-00 no banco de dados não estão conseguindo realizar o login adequadamente no sistema.

2024-03-20 15:39 UTC, nilsonLazarin commented
> Funcionários cujo o CPF foi registrado no formato 00000000000 ao invés de 000.000.000-00 no banco de dados não estão conseguindo realizar o login adequadamente no sistema.

Resolvido. O módulo sócio quando importava do JUNO uma doação, adicionava automaticamente uma pessoa. Entretanto no JUNO, não eram considerados os "...-". Todos os cadastros de pessoa foram ajustados, usando o código abaixo

```
UPDATE wegia.pessoa
SET CPF = CONCAT(
    LEFT(CPF, 3), '.', 
    SUBSTRING(CPF, 4, 3), '.', 
    SUBSTRING(CPF, 7, 3), '-', 
    RIGHT(CPF, 2)
)
WHERE cpf NOT LIKE '%.%';
```

2024-03-20 15:48 UTC, nilsonLazarin commented
@GabrielPintoSouza 
Demo do WeGIA atualizada. Favor validar as alterações para liberação do Merge na Main.
![image](https://github.com/nilsonLazarin/WeGIA/assets/32855001/8ca198b5-6c84-4a48-afe0-2d1990e6730f)

2024-03-21 12:58 UTC, nilsonLazarin approved these changes

2024-03-21 12:59 UTC, merged